//! Build guard: the web UI's compiled CSS (`assets/app.css`) is generated by
//! `cd web && npm run build` from `assets/index.html` (Tailwind scans the markup for class
//! names) and is gitignored. It's embedded into the binary via `rust-embed`. If it's missing,
//! the app still builds but serves an unstyled 404 for `/app.css` — a confusing, silent
//! failure. Turn that into a visible build warning. Also warn when it's merely **stale**: a
//! class added to `index.html` (e.g. `max-h-40`) after the last CSS build silently renders as
//! if the class didn't exist — no error, just wrong layout — until someone happens to rebuild.

use std::path::Path;

fn main() {
    let css = Path::new("assets/app.css");
    let html = Path::new("assets/index.html");
    if !css.exists() {
        println!(
            "cargo:warning=assets/app.css is missing — run `cd web && npm install && npm run build` \
             before building, or the UI will be unstyled."
        );
    } else if newer(html, css) {
        println!(
            "cargo:warning=assets/app.css is older than assets/index.html — run `cd web && npm run \
             build` or the UI may render with classes missing from the compiled CSS."
        );
    }
    // Rebuild if either the compiled CSS or the markup it's compiled from changes, so the
    // staleness check above actually re-runs when it matters.
    println!("cargo:rerun-if-changed=assets/app.css");
    println!("cargo:rerun-if-changed=assets/index.html");
}

/// Whether `a`'s mtime is strictly newer than `b`'s. Any I/O failure (missing file, unsupported
/// platform) is treated as "can't tell" rather than a false warning.
fn newer(a: &Path, b: &Path) -> bool {
    let mtime = |p: &Path| p.metadata().and_then(|m| m.modified()).ok();
    matches!((mtime(a), mtime(b)), (Some(a), Some(b)) if a > b)
}
