//! Build guard: the web UI's compiled CSS (`assets/app.css`) is generated by
//! `cd web && npm run build` and is gitignored. It's embedded into the binary via
//! `rust-embed`. If it's missing, the app still builds but serves an unstyled 404 for
//! `/app.css` — a confusing, silent failure. Turn that into a visible build warning.

use std::path::Path;

fn main() {
    let css = Path::new("assets/app.css");
    if !css.exists() {
        println!(
            "cargo:warning=assets/app.css is missing — run `cd web && npm install && npm run build` \
             before building, or the UI will be unstyled."
        );
    }
    // Rebuild if the asset appears/changes.
    println!("cargo:rerun-if-changed=assets/app.css");
}
