//! Build guard: the web UI's compiled CSS (`assets/app.css`) is generated by
//! `cd web && npm run build` from `assets/index.html` (Tailwind scans the markup for class
//! names) and is gitignored. It's embedded into the binary via `rust-embed`. If it's missing,
//! the app still builds but serves an unstyled 404 for `/app.css` — a confusing, silent
//! failure. Turn that into a visible build warning. Also warn when it's merely **stale**: a
//! class added to `index.html` (e.g. `max-h-40`) after the last CSS build silently renders as
//! if the class didn't exist — no error, just wrong layout — until someone happens to rebuild.

use std::path::Path;

fn main() {
    warn_on_toolchain_mismatch();

    let css = Path::new("assets/app.css");
    let html = Path::new("assets/index.html");
    if !css.exists() {
        println!(
            "cargo:warning=assets/app.css is missing — run `cd web && npm install && npm run build` \
             before building, or the UI will be unstyled."
        );
    } else if newer(html, css) {
        println!(
            "cargo:warning=assets/app.css is older than assets/index.html — run `cd web && npm run \
             build` or the UI may render with classes missing from the compiled CSS."
        );
    }
    // Rebuild if either the compiled CSS or the markup it's compiled from changes, so the
    // staleness check above actually re-runs when it matters.
    println!("cargo:rerun-if-changed=assets/app.css");
    println!("cargo:rerun-if-changed=assets/index.html");
}

/// Warn when the compiler running this build is not the one `rust-toolchain.toml` pins.
///
/// The pin only takes effect through rustup's shims. If another `cargo`/`rustc` comes first on
/// PATH — a Homebrew or distro install, say — the pin is silently ignored and the build happens
/// on whatever that toolchain is. Nothing announces this: the build succeeds, the tests pass, and
/// the version CI uses is simply not the version being used here. It cost a real session, where a
/// lint that only exists on the newer compiler appeared to be a defect in the code.
///
/// A warning, never an error. A contributor deliberately trying another compiler should not be
/// blocked; they should just be told which one they are actually on.
fn warn_on_toolchain_mismatch() {
    println!("cargo:rerun-if-changed=rust-toolchain.toml");

    let Ok(manifest) = std::fs::read_to_string("rust-toolchain.toml") else {
        return;
    };
    // `channel = "1.96.0"`. Only a pinned *version* is checkable — "stable" and "nightly" are
    // moving targets and comparing against them would warn on every correct build.
    let Some(pinned) = manifest
        .lines()
        .map(str::trim)
        .filter(|l| !l.starts_with('#'))
        .find_map(|l| l.strip_prefix("channel"))
        .and_then(|rest| rest.split('"').nth(1))
        .filter(|c| c.starts_with(|ch: char| ch.is_ascii_digit()))
    else {
        return;
    };

    // Cargo passes the compiler it is actually driving; that is the one whose version matters,
    // not whatever `rustc` resolves to in this build script's own PATH.
    let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".into());
    let Ok(out) = std::process::Command::new(rustc).arg("--version").output() else {
        return;
    };
    let version = String::from_utf8_lossy(&out.stdout);
    // "rustc 1.96.0 (ac68faa20 2026-05-25)" -> "1.96.0"
    let Some(actual) = version.split_whitespace().nth(1) else {
        return;
    };

    if actual != pinned {
        println!(
            "cargo:warning=building with rustc {actual}, but rust-toolchain.toml pins {pinned}. \
             The pin works through rustup's shims, so something earlier on PATH is shadowing \
             them (check `command -v cargo` — it should be under ~/.cargo/bin). CI uses {pinned}, \
             so lints and errors here may not match it."
        );
    }
}

/// Whether `a`'s mtime is strictly newer than `b`'s. Any I/O failure (missing file, unsupported
/// platform) is treated as "can't tell" rather than a false warning.
fn newer(a: &Path, b: &Path) -> bool {
    let mtime = |p: &Path| p.metadata().and_then(|m| m.modified()).ok();
    matches!((mtime(a), mtime(b)), (Some(a), Some(b)) if a > b)
}
