//! Generates the PowerShell that turns on remote administration safely — and does not run it.
//!
//! The failure mode this exists to prevent is not difficulty, it is **stopping halfway**.
//! `Enable-PSRemoting` starts a plaintext listener on 5985 and, per Microsoft's own
//! documentation, on client versions of Windows adds firewall rules for private and domain
//! networks that allow *unrestricted* remote access. Someone who runs that first command and gets
//! distracted has opened NTLM-over-HTTP to the whole network — on a machine whose threat model
//! names the person sitting at it. Every step after it exists to undo or replace part of that.
//!
//! A script is all-or-nothing. It also cannot be mis-transcribed, and it carries this machine's
//! real hostname rather than a placeholder the reader has to substitute.
//!
//! **It prints; it never executes.** Enabling remote administration is a decision about the
//! machine as a whole, not about screen time, so it stays the parent's to make and to read first.
//! Nestwatch configuring a general-purpose admin channel would also make Nestwatch responsible
//! for one, which is a long way outside what this tool is.

/// Render the setup script for `host`.
///
/// Pure, so the generated commands are testable without a Windows machine — which matters here,
/// because a wrong line in a security setup script is worse than no script at all.
pub fn script(host: &str) -> String {
    format!(
        r#"# ---------------------------------------------------------------------------
# Nestwatch — enable remote administration over HTTPS
#
# Generated by `nestwatch remote-setup` for: {host}
#
# Run this on THIS PC, in an elevated PowerShell, as one script. Do not run it a
# line at a time: the first command opens a plaintext listener that later lines
# close, so stopping partway leaves the machine worse off than not starting.
#
# Read docs/REMOTE-UPDATE.md before running it. In particular: if your child's
# account is a local administrator, fix that first — everything here opens an
# administrative way in, and he would be able to use it himself.
# ---------------------------------------------------------------------------

$ErrorActionPreference = 'Stop'

if (-not ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()
  ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
  throw 'Run this in an elevated PowerShell (Run as administrator).'
}}

Write-Host '1/6  Enabling remoting (this opens a plaintext listener; step 3 removes it)...'
Enable-PSRemoting -Force | Out-Null

Write-Host '2/6  Creating a certificate for {host}...'
$cert = New-SelfSignedCertificate -DnsName '{host}' -CertStoreLocation Cert:\LocalMachine\My

Write-Host '3/6  Listening on HTTPS only...'
New-Item -Path WSMan:\localhost\Listener -Transport HTTPS -Address * `
         -CertificateThumbPrint $cert.Thumbprint -Force | Out-Null
# Remove the plaintext listener Enable-PSRemoting just created.
winrm delete winrm/config/Listener?Address=*+Transport=HTTP 2>$null | Out-Null

Write-Host '4/6  Restricting the firewall...'
# Allow 5986 from this subnet only, on Private networks only.
New-NetFirewallRule -DisplayName 'Nestwatch WinRM HTTPS (LAN only)' `
    -Direction Inbound -Protocol TCP -LocalPort 5986 `
    -RemoteAddress LocalSubnet -Profile Private -Action Allow | Out-Null

# Disable every rule that would admit plaintext WinRM. Matched on the port, not on a
# name: Windows localises DisplayName, and the built-in rules differ between versions.
Get-NetFirewallRule | Where-Object {{
    ($_ | Get-NetFirewallPortFilter).LocalPort -eq 5985
}} | Set-NetFirewallRule -Enabled False

Write-Host '5/6  Verifying...'
$listeners = (winrm enumerate winrm/config/Listener) -join "`n"
if ($listeners -match 'Transport = HTTP\b') {{
  throw 'A plaintext HTTP listener is still present. Do not use this until that is resolved.'
}}
if ($listeners -notmatch 'Transport = HTTPS') {{
  throw 'No HTTPS listener was created.'
}}

Write-Host '6/6  Exporting the certificate for your laptop...'
$out = Join-Path $env:PUBLIC 'nestwatch-winrm.cer'
Export-Certificate -Cert $cert -FilePath $out | Out-Null

Write-Host ''
Write-Host 'Done. HTTPS only, restricted to this subnet.'
Write-Host ''
Write-Host ('  Certificate thumbprint : ' + $cert.Thumbprint)
Write-Host ('  Certificate exported to: ' + $out)
Write-Host ''
Write-Host 'On your laptop, copy that file over, then in an elevated PowerShell:'
Write-Host ''
Write-Host '  # Compare this against the thumbprint above BEFORE importing.'
Write-Host '  (Get-PfxCertificate -FilePath .\nestwatch-winrm.cer).Thumbprint'
Write-Host '  Import-Certificate -FilePath .\nestwatch-winrm.cer -CertStoreLocation Cert:\LocalMachine\Root'
Write-Host ''
Write-Host '  $s = New-PSSession -ComputerName {host} -UseSSL -Credential (Get-Credential)'
Write-Host ''
Write-Host 'Comparing the thumbprint is what makes this safe. Never use -SkipCACheck.'
Write-Host ''
Write-Host 'Turn it off again when you are done — see the teardown script in'
Write-Host 'docs/REMOTE-UPDATE.md, or run: nestwatch remote-setup --off'
"#
    )
}

/// The teardown, generated the same way so it cannot drift from the setup above.
pub fn teardown_script() -> String {
    r#"# ---------------------------------------------------------------------------
# Nestwatch — turn remote administration back off
#
# Run on the monitored PC, elevated. Leaving remoting on between updates is a
# permanent entry point for something used a few times a year.
# ---------------------------------------------------------------------------

$ErrorActionPreference = 'Continue'

Disable-PSRemoting -Force

# Disable-PSRemoting leaves the listener, the firewall rule and the service behind,
# so none of the following is redundant.
winrm delete winrm/config/Listener?Address=*+Transport=HTTPS 2>$null | Out-Null

Get-NetFirewallRule -DisplayName 'Nestwatch WinRM HTTPS (LAN only)' -ErrorAction SilentlyContinue |
    Set-NetFirewallRule -Enabled False

Stop-Service WinRM -ErrorAction SilentlyContinue
Set-Service WinRM -StartupType Manual

Write-Host 'Remote administration is off. Re-run the setup script when you next need it.'
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The whole point is that it is one script, in the right order. `Enable-PSRemoting` opens a
    /// plaintext listener; the lines that close it must come after, or a partial run leaves the
    /// machine exposed rather than merely unconfigured.
    #[test]
    fn the_plaintext_listener_is_closed_after_it_is_opened() {
        let s = script("TEST-PC");
        let opened = s.find("Enable-PSRemoting").expect("must enable remoting");
        let closed = s
            .find("Transport=HTTP\n")
            .or_else(|| s.find("Transport=HTTP "))
            .expect("must delete the plaintext listener");
        assert!(
            opened < closed,
            "the plaintext listener must be removed after it is created, not before"
        );
    }

    /// A run that stops early must not be silently accepted, and a wrong port must not be
    /// silently allowed. Both are checked inside the script rather than left to the reader.
    #[test]
    fn the_script_verifies_itself_and_fails_loudly() {
        let s = script("TEST-PC");
        assert!(
            s.contains("$ErrorActionPreference = 'Stop'"),
            "must abort on error"
        );
        assert!(s.contains("IsInRole"), "must check it is elevated");
        assert!(
            s.contains("throw 'A plaintext HTTP listener is still present."),
            "must fail if HTTP survived"
        );
        assert!(s.contains("throw 'No HTTPS listener was created."));
    }

    /// The advice this script replaces is "add it to TrustedHosts and skip the certificate
    /// check". Neither may be *executed*.
    ///
    /// Checked against the executable lines only. The script deliberately names `-SkipCACheck` in
    /// a warning telling the reader never to use it — a blunt substring test cannot tell that
    /// from actually using it, and would push the warning out of the script to stay green.
    #[test]
    fn it_never_executes_the_unsafe_shortcuts() {
        let executable = |s: &str| -> String {
            s.lines()
                .map(str::trim)
                .filter(|l| !l.starts_with('#'))
                // Write-Host lines are output for the reader, not commands against the machine.
                .filter(|l| !l.starts_with("Write-Host"))
                .collect::<Vec<_>>()
                .join("\n")
        };

        for s in [script("TEST-PC"), teardown_script()] {
            let code = executable(&s);
            for bad in [
                "SkipCACheck",
                "SkipCNCheck",
                "TrustedHosts",
                "-RemoteAddress Any",
            ] {
                assert!(
                    !code.contains(bad),
                    "the script must never run {bad:?}; found in:\n{code}"
                );
            }
        }

        // And the warning must survive: it is the single most common piece of bad advice online.
        assert!(
            script("TEST-PC").contains("Never use -SkipCACheck"),
            "the script should still tell the reader not to reach for it"
        );
    }

    /// Restrictions that must survive any future edit: HTTPS only, this subnet only, private
    /// profile only. Each is one word away from being much wider.
    #[test]
    fn the_firewall_opening_stays_narrow() {
        let s = script("TEST-PC");
        assert!(s.contains("-LocalPort 5986"), "HTTPS port only");
        assert!(s.contains("-RemoteAddress LocalSubnet"), "this subnet only");
        assert!(s.contains("-Profile Private"), "private networks only");
        assert!(
            !s.contains("-RemoteAddress Any"),
            "must never open to any address"
        );
        // The plaintext port must be shut, and matched by port rather than by a localised name.
        assert!(s.contains("LocalPort -eq 5985"));
        assert!(
            !s.contains("DisplayName -like"),
            "rule names are localised; match on the port"
        );
    }

    /// The hostname is substituted, not left as a placeholder for the reader to replace -- a
    /// mismatch between the certificate name and the name typed at connect time is the most
    /// likely way this ends in someone reaching for -SkipCNCheck.
    #[test]
    fn the_real_hostname_is_baked_in() {
        let s = script("CAMDERE-WINDOWS");
        assert!(s.contains("-DnsName 'CAMDERE-WINDOWS'"), "certificate name");
        assert!(
            s.contains("-ComputerName CAMDERE-WINDOWS -UseSSL"),
            "and the same name in the connect line"
        );
        assert!(!s.contains("<hostname>"), "no placeholder should survive");
    }

    /// Teardown has to undo what setup did. `Disable-PSRemoting` alone leaves the listener, the
    /// firewall rule and the service running, which reads as "off" and is not.
    #[test]
    fn teardown_removes_everything_setup_created() {
        let t = teardown_script();
        assert!(t.contains("Disable-PSRemoting"));
        assert!(t.contains("Transport=HTTPS"), "the listener setup created");
        assert!(
            t.contains("Nestwatch WinRM HTTPS (LAN only)"),
            "the firewall rule setup created, by the exact name setup used"
        );
        assert!(t.contains("Stop-Service WinRM"), "and the service itself");

        // The name must match between the two scripts, or teardown silently does nothing.
        let rule = "Nestwatch WinRM HTTPS (LAN only)";
        assert!(script("X").contains(rule) && t.contains(rule));
    }
}
